# Change these first
owner: hykilpikonna # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
    # Hosted on ovh.hydev.org
  - name: HyDEV - Pastebin
    url: https://bin.hydev.org
  - name: HyDEV - Lisho
    url: https://sh.hydev.org
  - name: HyDEV - CDN
    url: https://cdn.hydev.org/backup/
    
    # Hosted on daisy.hydev.org
  - name: Daisy - Minecraft
    url: https://mc.hydev.org/dynmap
  - name: Daisy - Overleaf Self-Hosted
    url: https://tex.hydev.org
  - name: Daisy - Voice Tools Bot Backend
    url: https://voice-backend.hydev.org
  - name: Daisy - Owncast Video Streaming
    url: https://cast.hydev.org
  - name: Daisy - Grafana System Monitoring
    url: https://gf.hydev.org
  - name: Daisy - ArchLinux Repo
    url: https://arch.hydev.org
    
    # Servers
  - name: "Server - 🇨🇦 OVH Montreal"
    check: "tcp-ping"
    url: ovh.hydev.org
    port: 22
  - name: "Server - 🇨🇦 Bell Toronto 'Daisy'"
    url: https://daisy-ddns.hydev.org/health/
  - name: "Server - 🇱🇺 GCore Luxembourg"
    check: "tcp-ping"
    url: lux.hydev.org
    port: 22
  - name: "Server - 🇨🇳 Aliyun 杭州"
    check: "tcp-ping"
    url: cn.hydev.org
    port: 22
    
    # Package repository servers for MCPM
  - name: MCPRS - Bell
    url: https://mcprs.hydev.org
    
    # Github Pages sites
  - name: GH - Veracross Analyzer Demo
    url: https://demo.vera.hydev.org
  - name: GH - Arcaea Steps Calculator
    url: https://arcaea.hydev.org
  - name: GH - Base 3000
    url: https://b3k.hydev.org
  - name: GH - Cellular Automata
    url: https://cellular.hydev.org
  - name: GH - CSC110 Research Report
    url: https://csc110.hydev.org/
  - name: GH - Clash Proxy Config
    url: https://clash.hydev.org/clash.yml
  - name: GH - NyaaMemo Demo
    url: https://nyaa.hydev.org/

status-website:
  cname: uptime.hydev.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HyDEV Status
  introTitle: "HyDEV Service Status"
  introMessage: "This is a status page monitoring all HyDEV services, powered by [Upptime](https://github.com/upptime/upptime)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/hykilpikonna

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
